export interface ChatUserInfo{
    uiNum?:number;
    uiId?:String;
    uiPwd?:String;
    uiName?:String;
    uiEmail?:String;
    uiMobile?:String;
    uiZonecode?:String;
    uiRoadaddr?:String;
    uiDetailAddr?:String;
    uiRole?:String;
    credat?:String;
    lmodat?:String;
    active?:String;
    uiDesc?:String;
    uiImgName?:String;
    uiImgPath?:String;
    file?:String;
    token?:String;
    riRank?:number;
    riComment?:Array<Array<String>>;
    login?:string;
}